#
# checklinks.py - every cross-page link resolves, ANCHOR INCLUDED.
#
#   python checklinks.py <markdown-dir> <html-dir>
#
# The markdown side can only prove the page exists.  An anchor is generated by
# the renderer's own slugify - "OS.EXECUTE" becomes "osexecute", not
# "os-execute" - so the only way to know a "#..." link lands anywhere is to
# read the rendered pages.  One wrong anchor was written this session and this
# is what caught it.
#
import os
import re
import sys

MD = sys.argv[1]
HTML = sys.argv[2]

ids = {}
for name in sorted(os.listdir(HTML)):
    if not name.lower().endswith('.html'):
        continue
    with open(os.path.join(HTML, name), 'r', encoding='utf-8') as f:
        ids[name] = set(re.findall(r'id="([^"]+)"', f.read()))

print('checklinks: %d rendered page(s) read' % len(ids))
if not ids:
    sys.exit('checklinks: no rendered pages - refusing to report a clean result')

LINK = re.compile(r'\]\((\d\d-[a-z0-9.-]+\.html)(#[A-Za-z0-9_-]+)?\)')

bad = 0
checked = 0
for name in sorted(os.listdir(MD)):
    if not name.lower().endswith('.md'):
        continue
    with open(os.path.join(MD, name), 'r', encoding='utf-8') as f:
        txt = f.read()
    for page, anchor in LINK.findall(txt):
        checked += 1
        if page not in ids:
            print('  MISSING PAGE   %-28s -> %s' % (name, page))
            bad += 1
            continue
        if anchor and anchor[1:] not in ids[page]:
            print('  MISSING ANCHOR %-28s -> %s%s' % (name, page, anchor))
            bad += 1

print('checklinks: %d link(s) checked, %d broken' % (checked, bad))
if checked == 0:
    sys.exit('checklinks: no links found at all - that cannot be right')
sys.exit(1 if bad else 0)
